/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.email.view;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import lk.ijse.email.dto.EmailDTO;

/**
 *
 * @author Chamini
 */
public class NewForm extends javax.swing.JPanel {

    /**
     * Creates new form NewForm
     */
    
    File f;
    NewForm() {
        initComponents();
        txtTo.requestFocus();
        lblPath.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanalNew = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        txtCC = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        btnDiscard = new javax.swing.JButton();
        lblAttached = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubject = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaMessage1 = new org.jdesktop.swingx.JXTextArea();

        setLayout(null);

        PanalNew.setBackground(new java.awt.Color(204, 204, 204));
        PanalNew.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(176, 168, 168));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("To");
        jLabel1.setOpaque(true);
        PanalNew.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 28, 41, 28));

        jLabel2.setBackground(new java.awt.Color(181, 179, 179));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cc");
        jLabel2.setOpaque(true);
        PanalNew.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 82, 40, 28));

        jSeparator1.setBackground(new java.awt.Color(59, 57, 57));
        PanalNew.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 64, 836, 7));

        jSeparator2.setBackground(new java.awt.Color(59, 57, 57));
        PanalNew.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 118, 836, -1));

        jLabel3.setBackground(new java.awt.Color(176, 168, 168));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Bcc");
        jLabel3.setOpaque(true);
        PanalNew.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 23, 41, -1));

        lblPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPathMouseClicked(evt);
            }
        });
        PanalNew.add(lblPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 300, 40));

        btnSend.setBackground(new java.awt.Color(0, 51, 51));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        PanalNew.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 554, 107, 34));

        txtCC.setOpaque(false);
        PanalNew.add(txtCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 84, 792, 28));

        txtTo.setOpaque(false);
        PanalNew.add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 30, 740, 28));

        btnDiscard.setBackground(new java.awt.Color(0, 51, 51));
        btnDiscard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDiscard.setText("Discard");
        PanalNew.add(btnDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 554, 106, 34));

        lblAttached.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Iconia_48(0)_128aa.png"))); // NOI18N
        lblAttached.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAttachedMouseClicked(evt);
            }
        });
        PanalNew.add(lblAttached, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 554, -1, 35));
        PanalNew.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 554, 60, 39));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/linecons_e01b(0)_64dd.png"))); // NOI18N
        PanalNew.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 554, -1, 31));

        jLabel4.setText("jLabel4");
        PanalNew.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, 30));

        txtSubject.setBackground(new java.awt.Color(204, 204, 204));
        txtSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSubject.setPrompt("Add Subject");
        PanalNew.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 790, 30));

        txtareaMessage1.setColumns(20);
        txtareaMessage1.setRows(5);
        jScrollPane1.setViewportView(txtareaMessage1);

        PanalNew.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 840, 370));

        add(PanalNew);
        PanalNew.setBounds(0, 0, 900, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        String to = txtTo.getText();
        String source=to;
        StringTokenizer stocken=new StringTokenizer(source,",");
        while(stocken.hasMoreTokens()){
			String token=stocken.nextToken();
			System.out.println(token);
		}
        String cc = txtCC.getText();
        String source1=cc;
        StringTokenizer stocken1=new StringTokenizer(source1,",");
        while(stocken1.hasMoreTokens()){
			String token=stocken1.nextToken();
			System.out.println(token);
		}
        String subject = txtSubject.getText();
        String message = txtareaMessage1.getText();
        
        EmailDTO email=new EmailDTO(source1, subject, subject, cc, to, to, to);
        
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void lblAttachedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttachedMouseClicked
        viewFileChooser();
    }//GEN-LAST:event_lblAttachedMouseClicked

    private void lblPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPathMouseClicked
        // TODO add your handling code here:
         FileInputStream fis1=null;
        try {
            fis1 = new FileInputStream(f);
           
            int code=fis1.read();//public int read()
            while(code!=-1){
                System.out.print((char)code);
                code=fis1.read();
                txtareaMessage1.setText(code+"");
                }
//           BufferedReader in  = new BufferedReader(new FileReader("f.in"));
//             String readLine = in.readLine();
//             while (readLine!=null) {
//                System.out.print(readLine);
//               readLine = in.readLine();
//                txtareaMessage.setText(readLine+"");
        
        
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
		
        
    }//GEN-LAST:event_lblPathMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanalNew;
    private javax.swing.JButton btnDiscard;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAttached;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPath;
    private javax.swing.JTextField txtCC;
    private org.jdesktop.swingx.JXTextField txtSubject;
    private javax.swing.JTextField txtTo;
    private org.jdesktop.swingx.JXTextArea txtareaMessage1;
    // End of variables declaration//GEN-END:variables

    private void viewFileChooser() {
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            f = chooser.getSelectedFile();
//            this.attachmentName = f.getName();
//            this.attachmentPath = f.getAbsolutePath();//dan mokdda karanna ona// meke file ek 
//            txtAttachment.setText(attachmentPath);
            System.out.println(f.getName());
            System.out.println(f.getAbsolutePath());
            
//            Icon icon = new ImageIcon(getClass().getResource("/image/file.png"));
            lblPath.setText(f.getName());
//            lblPath.setIcon(icon);
            lblPath.setVisible(true);
       
            
        } catch (NullPointerException e) {
            
        }              
    }     
}
